#include <iostream>
using namespace std;
main(){
int Add;
int Multiply;
int Subtract;
int Total;
int Number1;
int Number2;
int Number3;
int Number4;
int Number5;
int Number6;
int Number7;
int Number8;
int Number9;
int Number10;
int Number11;
int Number12;
int Number13;
int Number14;
int Number15;
int Final_Result;
cout<<"Number 1= ";
cin>>Number1;
cout<<"Number 2= ";
cin>>Number2;
cout<<"Number 3= ";
cin>>Number3;
cout<<"Number 4= ";
cin>>Number4;
cout<<"Number 5= ";
cin>>Number5;
cout<<"Number 6= ";
cin>>Number6;
cout<<"Number 7= ";
cin>>Number7;
cout<<"Number 8= ";
cin>>Number8;
cout<<"Number 9= ";
cin>>Number9;
cout<<"Number 10= ";
cin>>Number10;
cout<<"Number 11= ";
cin>>Number11;
cout<<"Number 12= ";
cin>>Number12;
cout<<"Number 13= ";
cin>>Number13;
cout<<"Number 14= ";
cin>>Number14;
cout<<"Number 15= ";
cin>>Number15;
Add=Number1+Number2+Number3+Number4 + Number5;
cout<<"Addition= "<< Add<<endl;
Multiply=Number6*Number7*Number8*Number9*Number10;
cout<<"Multiplication= "<< Multiply<<endl;
Subtract= Number11-Number12-Number13-Number14-Number15;
cout<<"Subtraction= "<< Subtract<<endl;
Total=Add+ Multiply;
cout<<"Total value= "<<Total<<endl;
Final_Result= Total-Subtract;
cout<<"Final Result= "<<Final_Result;
}

